---
title: "DIC Fisheries Project Figure 3"
author: "Rachael E. Blake"
date: "April 26, 2018"
output: html_document
---
<style>
p.caption {
  font-size: 1.6em;
}
</style>

```{r, include=FALSE, echo=FALSE}
source("./DIC_Fisheries_Project.R")

library(egg) 

```

```{r, echo=FALSE}

#######################################
### MAKE MY OWN BOXPLOT THEME 
theme_boxplot <- function(base_size = 12){
 theme_bw(base_size) %+replace%
   theme(legend.key.size=unit(15,"points"),
         legend.text=element_text(size=I(13)),
         legend.key=element_blank(),
         legend.title=element_blank(),
         legend.position="none",
         panel.border=element_rect(colour='black', fill = NA),
         axis.ticks.length=unit(1,"mm"),
         axis.text=element_text(size=15),
         axis.title.x=element_text(margin=unit(c(4,1,1,1), "mm"), size=17),
         axis.title.y=element_text(margin=unit(c(1,4,1,1), "mm"),size=17, angle=90),
         panel.grid.major=element_blank(),
         panel.grid.minor=element_blank(),
         strip.text.x=element_text(size=14),
         strip.background=element_rect(colour='black', fill='white'))
}  
##########################################

```


```{r, echo=FALSE, fig.width = 9, fig.height = 6, fig.cap="Boxplot showing number of species fished per year from 1990 - 2016.  Each box shows mean (horizontal line), quantiles 1 and 3 (box), and outliers (dots).", , fig.align="center"}

plot_alldiv2 <- ggplot(data=all_div2, aes(x=State, y=n)) + geom_boxplot() +
                theme_boxplot() + ylab("Number of species fished")

plot_alldiv2

```

